export const LOGIN_REQUEST_MADE = "LOGIN_REQUEST_MADE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const GROUP_REQUEST = "GROUP_REQUEST";
export const GROUP_REQUEST_SUCCESS = "GROUP_REQUEST_SUCCESS";
export const GROUP_REQUEST_FAILURE = "GROUP_REQUEST_FAILURE";
